version: '3.8'

services:
  api:
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - '3306'
    env_file:
      - .env
    volumes:
      - mysql_db_vol:/var/lib/mysql

volumes:
  mysql_db_vol:
